# 1 - Data Cleaning

In [10]:
import numpy as np
import pandas as pd
import csv

In [11]:
df = pd.read_csv('/Users/lamaayash/Downloads/Data Science Project/parkinsons_updrs.data')
df.head()

,subject#,age,sex,test_time,motor_UPDRS,total_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,...,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE
0,1,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,...,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,...,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,1,72,0,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,...,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,1,72,0,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,...,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,1,72,0,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,...,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5875 entries, 0 to 5874
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   subject#       5875 non-null   int64
 1   age            5875 non-null   int64
 2   sex            5875 non-null   int64
 3   test_time      5875 non-null   float64
 4   motor_UPDRS    5875 non-null   float64
 5   total_UPDRS    5875 non-null   float64
 6   Jitter(%)      5875 non-null   float64
 7   Jitter(Abs)    5875 non-null   float64
 8   Jitter:RAP     5875 non-null   float64
 9   Jitter:PPQ5    5875 non-null   float64
 10  Jitter:DDP     5875 non-null   float64
 11  Shimmer        5875 non-null   float64
 12  Shimmer(dB)    5875 non-null   float64
 13  Shimmer:APQ3   5875 non-null   float64
 14  Shimmer:APQ5   5875 non-null   float64
 15  Shimmer:APQ11  5875 non-null   float64
 16  Shimmer:DDA    5875 non-null   float64
 17  NHR            5875 non-null   float64
 18  HNR            5875 non-null   float64
 19  RPDE           5875 non-null   float64
 20  DFA            5875 non-null   float64
 21  PPE            5875 non-null   float64
dtypes: float64(19), int64(3)
memory usage: 1009.9 KB

# let's learn more about our features




subject# - Integer that uniquely identifies each subject 

age - Subject age 

sex - Subject gender '0' - male, '1' - female 

test_time - Time since recruitment into the trial. The integer part is the number of days since recruitment. 

motor_UPDRS - Clinician's motor UPDRS score, linearly interpolated 

total_UPDRS - Clinician's total UPDRS score, linearly interpolated 

Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP - Several measures of variation in fundamental frequency 

Shimmer,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA - Several measures of variation in amplitude 

NHR,HNR - Two measures of ratio of noise to tonal components in the voice 

RPDE - A nonlinear dynamical complexity measure 

DFA - Signal fractal scaling exponent 

PPE - A nonlinear measure of fundamental frequency variation

In [13]:
#42 subject * 150-200 voice note
df.shape

(5875, 22)

In [14]:
# Check the number of the subjects
df['subject#'].nunique()

42

In [15]:
copies = df.duplicated(subset=['subject#','age', 'sex', 'test_time', 'motor_UPDRS', 'total_UPDRS', 'Jitter(%)',
       'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP', 'Shimmer',
       'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5', 'Shimmer:APQ11',
       'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE'])

In [16]:
copies.value_counts()

False    5875
dtype: int64

fortunately no duplicates columns

In [17]:
df.columns

Index(['subject#', 'age', 'sex', 'test_time', 'motor_UPDRS', 'total_UPDRS',
       'Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP',
       'Shimmer', 'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'Shimmer:APQ11', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE'],
      dtype='object')

In [18]:
#we will drop 'subject' as long as we don't need it
df.drop(['subject#'],axis=1,inplace=True)

In [19]:
#check if any nulls in our data -luckily no there is no nulls
df.isnull().sum()

age              0
sex              0
test_time        0
motor_UPDRS      0
total_UPDRS      0
Jitter(%)        0
Jitter(Abs)      0
Jitter:RAP       0
Jitter:PPQ5      0
Jitter:DDP       0
Shimmer          0
Shimmer(dB)      0
Shimmer:APQ3     0
Shimmer:APQ5     0
Shimmer:APQ11    0
Shimmer:DDA      0
NHR              0
HNR              0
RPDE             0
DFA              0
PPE              0
dtype: int64

In [20]:
#Rename some colmuns to make it easier to use
df.rename(
    inplace=True,
    columns={
        'Jitter(%)':'Jitter',
        'Jitter(Abs)':'Jitter_Abc',
        'Jitter:RAP':'Jitter_RAP',
        'Jitter:PPQ5':'Jitter_PPQ5',
        'Jitter:DDP':'Jitter_DDP',
        'Shimmer(dB)':'Shimmer_dB',
        'Shimmer:APQ3':'Shimmer_APQ3',
        'Shimmer:APQ5':'Shimmer_APQ5',
        'Shimmer:APQ11':'Shimmer_APQ11',
        'Shimmer:DDA':'Shimmer_DDA'
    })

In [21]:
df.head(2)

,age,sex,test_time,motor_UPDRS,total_UPDRS,Jitter,Jitter_Abc,Jitter_RAP,Jitter_PPQ5,Jitter_DDP,...,Shimmer_dB,Shimmer_APQ3,Shimmer_APQ5,Shimmer_APQ11,Shimmer_DDA,NHR,HNR,RPDE,DFA,PPE
0,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,0.01204,...,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,0.00395,...,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810

In [22]:
# Confirm that our column renamed correctly - it did
df.columns

Index(['age', 'sex', 'test_time', 'motor_UPDRS', 'total_UPDRS', 'Jitter',
       'Jitter_Abc', 'Jitter_RAP', 'Jitter_PPQ5', 'Jitter_DDP', 'Shimmer',
       'Shimmer_dB', 'Shimmer_APQ3', 'Shimmer_APQ5', 'Shimmer_APQ11',
       'Shimmer_DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE'],
      dtype='object')

According to our dataset we have to divide our dataset into 2 models and work upon 2 individually

First : predict total_UPDRS

Second: predict motor_UPDRS

In [23]:
df1 = df.copy()
df2 = df.copy()

In [24]:
# Save output as CSV
df1.to_csv('/Users/lamaayash/df1.csv', index=False)
df2.to_csv('/Users/lamaayash/df2.csv', index=False)

# 2-Feature engineering

In [25]:
#import my clean data1
df = pd.read_csv('/Users/lamaayash/df1.csv')

In [26]:
#import my clean data2
df = pd.read_csv('/Users/lamaayash/df2.csv')

In [27]:
df1.head()

,age,sex,test_time,motor_UPDRS,total_UPDRS,Jitter,Jitter_Abc,Jitter_RAP,Jitter_PPQ5,Jitter_DDP,...,Shimmer_dB,Shimmer_APQ3,Shimmer_APQ5,Shimmer_APQ11,Shimmer_DDA,NHR,HNR,RPDE,DFA,PPE
0,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,0.01204,...,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,0.00395,...,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,72,0,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,0.00616,...,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,72,0,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,0.00573,...,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,72,0,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,0.00278,...,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361

In [28]:
df2.head()

,age,sex,test_time,motor_UPDRS,total_UPDRS,Jitter,Jitter_Abc,Jitter_RAP,Jitter_PPQ5,Jitter_DDP,...,Shimmer_dB,Shimmer_APQ3,Shimmer_APQ5,Shimmer_APQ11,Shimmer_DDA,NHR,HNR,RPDE,DFA,PPE
0,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,0.01204,...,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,0.00395,...,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,72,0,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,0.00616,...,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,72,0,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,0.00573,...,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,72,0,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,0.00278,...,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361

# Now let's learn about our first scale in this dataset

(UPDRS) indicate for UNIFIED PARKINSONâ€™S DISEASE RATING SCALE.

A score of 199 on the UPDRS scale represents the worst (total disability)

with a score of zero representing (no disability)

In [29]:
df1['total_UPDRS'].describe()

count    5875.000000
mean       29.018942
std        10.700283
min         7.000000
25%        21.371000
50%        27.576000
75%        36.399000
max        54.992000
Name: total_UPDRS, dtype: float64

the seconed scale in our dataset UPDRS
includes assess motor abnormalities such as rest tremor,

action tremor, rigidity, bradykinesia,gait and posture, and facial masking. 

The total motor UPDRS exam score ranges from 0 to 108.

In [30]:
df1['motor_UPDRS'].describe()

count    5875.000000
mean       21.296229
std         8.129282
min         5.037700
25%        15.000000
50%        20.871000
75%        27.596500
max        39.511000
Name: motor_UPDRS, dtype: float64

In [31]:
df1[['Jitter', 'Jitter_Abc', 'Jitter_RAP', 'Jitter_PPQ5', 'Jitter_DDP',
       'Shimmer', 'Shimmer_dB', 'Shimmer_APQ3', 'Shimmer_APQ5',
       'Shimmer_APQ11', 'Shimmer_DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE']].describe()

,Jitter,Jitter_Abc,Jitter_RAP,Jitter_PPQ5,Jitter_DDP,Shimmer,Shimmer_dB,Shimmer_APQ3,Shimmer_APQ5,Shimmer_APQ11,Shimmer_DDA,NHR,HNR,RPDE,DFA,PPE
count,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000,5875.000000
mean,0.006154,0.000044,0.002987,0.003277,0.008962,0.034035,0.310960,0.017156,0.020144,0.027481,0.051467,0.032120,21.679495,0.541473,0.653240,0.219589
std,0.005624,0.000036,0.003124,0.003732,0.009371,0.025835,0.230254,0.013237,0.016664,0.019986,0.039711,0.059692,4.291096,0.100986,0.070902,0.091498
min,0.000830,0.000002,0.000330,0.000430,0.000980,0.003060,0.026000,0.001610,0.001940,0.002490,0.004840,0.000286,1.659000,0.151020,0.514040,0.021983
25%,0.003580,0.000022,0.001580,0.001820,0.004730,0.019120,0.175000,0.009280,0.010790,0.015665,0.027830,0.010955,19.406000,0.469785,0.596180,0.156340
50%,0.004900,0.000035,0.002250,0.002490,0.006750,0.027510,0.253000,0.013700,0.015940,0.022710,0.041110,0.018448,21.920000,0.542250,0.643600,0.205500
75%,0.006800,0.000053,0.003290,0.003460,0.009870,0.039750,0.365000,0.020575,0.023755,0.032715,0.061735,0.031463,24.444000,0.614045,0.711335,0.264490
max,0.099990,0.000446,0.057540,0.069560,0.172630,0.268630,2.107000,0.162670,0.167020,0.275460,0.488020,0.748260,37.875000,0.966080,0.865600,0.731730

# Here we go our data is ready for EDA.